export const PRIVATE_PDF_DOWNLOAD_PRICE_INR = 4;
export const MARKETPLACE_PRICE_MIN_INR = 4;
export const MARKETPLACE_PRICE_MAX_INR = 10;
export const ADMIN_COMMISSION_PERCENT = 30;
export const SELLER_COMMISSION_PERCENT = 70;
